//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BlazeClawMFC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_DASHBOARD_CRON_WND          105
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BlazeClawMFCTYPE            130
#define ID_WINDOW_MANAGER               131
#define IDS_DASHBOARD_WND               132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               152
#define IDR_WINDOWS_MENU                153
#define ID_PROPERTIES1                  154
#define ID_PROPERTIES2                  155
#define ID_EXPAND_ALL                   156
#define IDS_FILE_VIEW                   157
#define IDS_CLASS_VIEW                  158
#define IDS_OUTPUT_WND                  159
#define IDS_PROPERTIES_WND              160
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         211
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   212
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  213
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 214
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   215
#define ID_VIEW_APPLOOK_WINDOWS_7       216
#define ID_TOOLS_OPTIONS                217
#define ID_VIEW_CAPTION_BAR             218
#define IDB_INFO                        219
#define IDS_CAPTION_BUTTON              220
#define IDS_CAPTION_BUTTON_TIP          221
#define IDS_CAPTION_TEXT                222
#define IDS_CAPTION_IMAGE_TIP           223
#define IDS_CAPTION_IMAGE_TEXT          224
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   270
#define IDS_DEBUG_TAB                   271
#define IDS_FIND_TAB                    272
#define IDS_EXPLORER                    273
#define IDS_EDIT_MENU                   274
#define IDR_RIBBON                      275
#define IDD_OVERVIEW_DIALOG             276
#define IDD_INSTANCE_DIALOG             277
#define IDD_SESSION_DIALOG              278
#define IDD_USAGE_DIALOG                279
#define IDD_TASK_DIALOG                 280
#define IDD_SKILL_DIALOG                281
#define IDD_LOG_DIALOG                  282
#define IDD_QRCODE_LOGIN                283
#define IDD_LOGIN_DIALOG                284
#define IDD_DIALOG1                     285
#define IDD_NEWTAB_DIALOG               286
#define IDI_DASHBOARD_WND               298
#define IDI_DASHBOARD_WND_HC            299
#define IDI_DASHBOARD_OVERVIEW_WND_HC	300
#define IDI_DASHBOARD_OVERVIEW_WND		301
#define IDI_DASHBOARD_TOOLS_WND_HC		302
#define IDI_DASHBOARD_TOOLS_WND			303
#define IDI_DASHBOARD_FILES_WND_HC		304
#define IDI_DASHBOARD_FILES_WND			305
#define IDI_DASHBOARD_SKILLS_WND_HC		306
#define IDI_DASHBOARD_SKILLS_WND		307
#define IDI_DASHBOARD_CHANNELS_WND_HC	308
#define IDI_DASHBOARD_CHANNELS_WND		309
#define IDI_DASHBOARD_CRON_WND_HC       310
#define IDI_DASHBOARD_CRON_WND          311
#define IDI_DASHBOARD_DREAMING_WND_HC	312
#define IDI_DASHBOARD_DREAMING_WND		313
#define IDI_DASHBOARD_NODES_WND_HC		314
#define IDI_DASHBOARD_NODES_WND			315
#define IDI_DASHBOARD_INSTANCES_WND_HC	316
#define IDI_DASHBOARD_INSTANCES_WND		317
#define IDI_DASHBOARD_USAGE_WND_HC		318
#define IDI_DASHBOARD_USAGE_WND			319
#define IDI_DASHBOARD_DEVICES_WND_HC	320
#define IDI_DASHBOARD_DEVICES_WND		321
#define IDS_DASHBOARD_OVERVIEW_WND      330
#define IDS_DASHBOARD_TOOLS_WND         331
#define IDS_DASHBOARD_FILES_WND         332
#define IDS_DASHBOARD_SKILLS_WND        333
#define IDS_DASHBOARD_CHANNELS_WND      334
#define IDS_DASHBOARD_DREAMING_WND      335
#define IDS_DASHBOARD_NODES_WND         336
#define IDS_DASHBOARD_INSTANCES_WND     337
#define IDS_DASHBOARD_USAGE_WND         338
#define IDS_STRING338                   338
#define IDS_DASHBOARD_DEVICES_WND       339
#define IDC_STATIC_TITLE                1000
#define IDC_STATIC_DESCRIPTION          1001
#define IDC_GROUP_GATEWAY               1002
#define IDC_STATIC_GATEWAY_DESC         1003
#define IDC_STATIC_WS_URL               1004
#define IDC_EDIT_WS_URL                 1005
#define IDC_STATIC_GATEWAY_TOKEN        1006
#define IDC_EDIT_GATEWAY_TOKEN          1007
#define IDC_STATIC_PASSWORD             1008
#define IDC_EDIT_PASSWORD               1009
#define IDC_STATIC_SESSION_KEY          1010
#define IDC_EDIT_SESSION_KEY            1011
#define IDC_STATIC_LANGUAGE             1012
#define IDC_COMBO_LANGUAGE              1013
#define IDC_BUTTON_CONNECT              1014
#define IDC_BUTTON_REFRESH              1015
#define IDC_STATIC_HINT                 1016
#define IDC_STATIC_INST_MAIN_TITLE      1017
#define IDC_STATIC_INST_MAIN_DESC       1018
#define IDC_GROUP_CONN_INST             1019
#define IDC_STATIC_CONN_SUBTITLE        1020
#define IDC_BUTTON_INST_REFRESH         1021
#define IDC_GROUP_INSTANCE_CARD         1022
#define IDC_STATIC_INSTANCE_DETAIL      1023
#define IDC_STATIC_INSTANCE_TAGS        1024
#define IDC_STATIC_INST_STATUS_JUST     1025
#define IDC_STATIC_INST_STATUS_LAST     1026
#define IDC_STATIC_INST_STATUS_BEACON   1027
#define IDC_STATIC_SESS_MAIN_TITLE      1028
#define IDC_STATIC_SESS_MAIN_DESC       1029
#define IDC_GROUP_SESS_CARD             1030
#define IDC_STATIC_SESS_EN_SUBTITLE     1031
#define IDC_BUTTON_SESS_REFRESH         1032
#define IDC_STATIC_ACTIVE_WITHIN_LABEL  1033
#define IDC_EDIT_ACTIVE_WITHIN_SEC      1034
#define IDC_STATIC_LIMIT_LABEL          1035
#define IDC_EDIT_LIMIT                  1036
#define IDC_CHECK_INCLUDE_GLOBAL        1037
#define IDC_CHECK_INCLUDE_UNKNOWN       1038
#define IDC_STATIC_SCORE_LABEL          1039
#define IDC_STATIC_HDR_KEY              1040
#define IDC_STATIC_HDR_LABEL            1041
#define IDC_STATIC_HDR_KIND             1042
#define IDC_STATIC_HDR_UPDATED          1043
#define IDC_STATIC_HDR_INDEX            1044
#define IDC_STATIC_HDR_THINKING         1045
#define IDC_STATIC_HDR_INSTANCE         1046
#define IDC_STATIC_HDR_REMAINING        1047
#define IDC_STATIC_HDR_ACTIONS          1048
#define IDC_STATIC_ROW_KEY              1049
#define IDC_EDIT_ROW_LABEL              1050
#define IDC_STATIC_ROW_KIND             1051
#define IDC_STATIC_ROW_UPDATED          1052
#define IDC_STATIC_ROW_INDEX            1053
#define IDC_COMBO_ROW_THINKING          1054
#define IDC_COMBO_ROW_INSTANCE          1055
#define IDC_COMBO_ROW_REMAINING         1056
#define IDC_BUTTON_ROW_DELETE           1057
#define IDC_STATIC_USAGE_MAIN_TITLE     1058
#define IDC_STATIC_USAGE_MAIN_DESC      1059
#define IDC_BUTTON_USAGE_TODAY          1060
#define IDC_BUTTON_USAGE_7D             1061
#define IDC_BUTTON_USAGE_30D            1062
#define IDC_EDIT_USAGE_DATE_FROM        1063
#define IDC_EDIT_USAGE_DATE_TO          1064
#define IDC_COMBO_USAGE_SCOPE           1065
#define IDC_RADIO_USAGE_TOKENS          1066
#define IDC_RADIO_USAGE_COST            1067
#define IDC_BUTTON_USAGE_REFRESH_TOP    1068
#define IDC_BUTTON_USAGE_EXPORT         1069
#define IDC_EDIT_USAGE_FILTER           1070
#define IDC_STATIC_USAGE_TIP            1071
#define IDC_GROUP_ACTIVITY_TIME         1072
#define IDC_STATIC_ACTIVITY_TITLE       1073
#define IDC_STATIC_ACTIVITY_SUB         1074
#define IDC_STATIC_ACTIVITY_TOKEN_COUNT 1075
#define IDC_STATIC_ACTIVITY_EMPTY       1076
#define IDC_GROUP_DAILY_USAGE           1077
#define IDC_STATIC_DAILY_TITLE          1078
#define IDC_STATIC_DAILY_EMPTY          1079
#define IDC_GROUP_USAGE_SESSIONS_PANEL  1080
#define IDC_STATIC_USAGE_SESS_TITLE     1081
#define IDC_STATIC_USAGE_SESS_COUNT     1082
#define IDC_BUTTON_USAGE_JUMP           1083
#define IDC_BUTTON_USAGE_VIEW           1083
#define IDC_BUTTON_USAGE_ERRORS         1084
#define IDC_BUTTON_USAGE_Recently       1084
#define IDC_BUTTON_USAGE_ALL_FILTER     1085
#define IDC_STATIC_USAGE_RECENT         1086
#define IDC_COMBO_USAGE_SORT            1087
#define IDC_BUTTON_USAGE_SESS_REFRESH   1088
#define IDC_STATIC_USAGE_SESS_EMPTY     1089
#define IDC_STATIC_USAGE_TO_LABEL       1090
#define IDC_STATIC_TASK_MAIN_TITLE      1091
#define IDC_STATIC_TASK_MAIN_DESC       1092
#define IDC_STATIC_SUM_PROXY_LBL        1093
#define IDC_STATIC_SUM_PROXY_VAL        1094
#define IDC_STATIC_SUM_COUNT_LBL        1095
#define IDC_STATIC_SUM_COUNT_VAL        1096
#define IDC_STATIC_SUM_NEXT_LBL         1097
#define IDC_STATIC_SUM_NEXT_VAL         1098
#define IDC_BUTTON_TASK_REFRESH_TOP     1099
#define IDC_GROUP_TASK_LIST             1100
#define IDC_EDIT_TASK_LIST_SEARCH       1101
#define IDC_COMBO_TASK_STARTUP          1102
#define IDC_COMBO_TASK_SCHEDULE         1103
#define IDC_COMBO_TASK_CONTROL          1104
#define IDC_COMBO_TASK_SORT             1105
#define IDC_COMBO_TASK_SORT_DIR         1106
#define IDC_BUTTON_TASK_LIST_SEARCH     1107
#define IDC_STATIC_TASK_LIST_EMPTY      1108
#define IDC_GROUP_RUN_HISTORY           1109
#define IDC_COMBO_HIST_CYCLE            1110
#define IDC_COMBO_HIST_HEALTH           1111
#define IDC_COMBO_HIST_SORT             1112
#define IDC_COMBO_HIST_STATUS           1113
#define IDC_COMBO_HIST_FILTER           1114
#define IDC_STATIC_HIST_EMPTY           1115
#define IDC_GROUP_CREATE_OUTER          1116
#define IDC_STATIC_CREATE_SUB           1117
#define IDC_GROUP_TASK_BASIC            1118
#define IDC_EDIT_TASK_NAME              1119
#define IDC_EDIT_TASK_DESC              1120
#define IDC_EDIT_TASK_FILE              1121
#define IDC_CHECK_TASK_NODES            1122
#define IDC_GROUP_TASK_SCHEDULE_FORM    1123
#define IDC_COMBO_SCHEDULE_TYPE         1124
#define IDC_EDIT_SCHEDULE_INTERVAL      1125
#define IDC_COMBO_SCHEDULE_UNIT         1126
#define IDC_GROUP_TASK_RUN_FORM         1127
#define IDC_EDIT_RUN_PATH               1128
#define IDC_COMBO_TRANSFER_MODE         1129
#define IDC_EDIT_RUN_MEMORY             1130
#define IDC_EDIT_CONCURRENCY            1131
#define IDC_EDIT_SCRIPT_ARGS            1132
#define IDC_GROUP_TASK_RESULT_FORM      1133
#define IDC_COMBO_RESULT_CHANNEL        1134
#define IDC_EDIT_RESULT_TAG             1135
#define IDC_EDIT_RESULT_RECIPIENTS      1136
#define IDC_BUTTON_TASK_CREATE          1137
#define IDC_STATIC_SKILL_PAGE_TITLE     1138
#define IDC_STATIC_SKILL_PAGE_DESC      1139
#define IDC_GROUP_SKILL_CARD            1140
#define IDC_STATIC_SKILL_CARD_TITLE     1150
#define IDC_STATIC_SKILL_CARD_SUB       1151
#define IDC_STATIC_SKILL_FILTER_LABEL   1152
#define IDC_EDIT_SKILL_SEARCH           1153
#define IDC_STATIC_SKILL_SHOWN_COUNT    1154
#define IDC_BUTTON_SKILL_REFRESH        1155
#define IDC_BTN_TOGGLE_BUILTIN          1156
#define IDC_LIST_SKILL_BUILTIN          1157
#define IDC_BTN_TOGGLE_EXTRA            1158
#define IDC_LIST_SKILL_EXTRA            1159
#define IDC_STATIC_LOG_PAGE_TITLE       1160
#define IDC_STATIC_LOG_PAGE_DESC        1161
#define IDC_BUTTON_LOG_REFRESH          1162
#define IDC_BUTTON_LOG_EXPORT           1163
#define IDC_STATIC_LOG_CARD_TITLE       1164
#define IDC_STATIC_LOG_CARD_SUB         1165
#define IDC_STATIC_LOG_FILTER_LABEL     1166
#define IDC_EDIT_LOG_SEARCH             1167
#define IDC_CHECK_LOG_AUTO_FOLLOW       1168
#define IDC_CHECK_LOG_TRACE             1169
#define IDC_CHECK_LOG_DEBUG             1170
#define IDC_CHECK_LOG_INFO              1171
#define IDC_CHECK_LOG_WARN              1172
#define IDC_CHECK_LOG_ERROR             1173
#define IDC_CHECK_LOG_FATAL             1174
#define IDC_STATIC_LOG_FILE_PATH        1175
#define IDC_LIST_LOG_ENTRIES            1176
#define IDC_BUTTON_TASK_LIST_RESET      1177
#define IDC_EDIT_HIST_TASK_NAME         1178
#define IDC_EDIT_HIST_DEPT              1179
#define IDC_BUTTON_HIST_QUERY           1180
#define IDC_COMBO_EXEC_MAP              1181
#define IDC_COMBO_EXEC_CONTENT          1182
#define IDC_EDIT_EXEC_TIMEOUT           1183
#define IDC_BUTTON_TASK_ADVANCED        1184
#define IDC_BUTTON_TASK_DELETE          1185
#define IDC_EDIT1                       1186
#define IDC_PROGRESS1                   1187
#define IDC_STATIC_QRCODE               1188
#define IDC_STATIC_STATUS               1189
#define ID_NEW_TAB_WEBVIEW_ONLY         2001
#define ID_NEW_TAB_WEBVIEW_CHAT         2002
#define IDC_STATIC_WEBVIEW_ONLY_DESC    2003
#define IDC_STATIC_WEBVIEW_CHAT_DESC    2004
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_DOC                     32771
#define ID_EDIT_OVERVIEW                32772
#define ID_EDIT_CHAT                    32773
#define ID_EDIT_LOG                     32774
#define ID_EDIT_DEBUG                   32775
#define ID_EDIT_CONF                    32776
#define ID_EDIT_NODE                    32777
#define ID_EDIT_SKILL                   32778
#define ID_EDIT_Agent                   32779
#define ID_EDIT_AGENT1                  32779
#define ID_EDIT_TASK                    32780
#define ID_EDIT_USG                     32781
#define ID_EDIT_SESSION                 32782
#define ID_EDIT_INST                    32783
#define ID_EDIT_CHANNEL                 32784
#define ID_EXTENSION_MODELSET           32786
#define IDC_PHONE_EDIT                  32787
#define IDC_CODE_EDIT                   32788
#define IDC_GET_CODE_BUTTON             32789
#define IDC_LOGIN_BUTTON                32790
#define IDC_BTN_REGIST                  32791
#define IDC_QRCODE_LOGIN_BUTTON         32792
#define ID_WINDOW_NEWAICHATVIEW         32793
#define ID_VIEW_TOOLS                   32794
#define ID_VIEW_DASHBOARDWND            32795
#define ID_VIEW_DASHBOARD_CRON_WND      32780
#define ID_EDIT_DASHBOARD               32797
#define ID_VIEW_DASHBOARD_OVERVIEW_WND  32772
#define ID_VIEW_DASHBOARD_TOOLS_WND     32784
#define ID_VIEW_DASHBOARD_FILES_WND     32783
#define ID_VIEW_DASHBOARD_SKILLS_WND    32782
#define ID_VIEW_DASHBOARD_CHANNELS_WND  32781
#define ID_VIEW_DASHBOARD_DREAMING_WND  32779
#define ID_VIEW_DASHBOARD_NODES_WND     32778
#define ID_VIEW_DASHBOARD_INSTANCES_WND 32777
#define ID_VIEW_DASHBOARD_USAGE_WND     32776
#define ID_VIEW_DASHBOARD_DEVICES_WND   32775
#define ID_EXTENSION_DEEPSEEK           40101
#define ID_WINDOW_NEW_WEBVIEW           40102
#define ID_WINDOW_NEW_WEBVIEW_CHAT      40103
#define ID_WINDOW_NEW_WEBVIEW_MARKDOWN  40104
#define IDD_APIKEY_DIALOG               41000
#define IDC_EDIT_APIKEY                 41001
#define IDC_STATIC_APIKEY_LABEL         41002
#define IDC_COMBO_PROVIDER              41003
#define IDC_STATIC_APIKEY_STATUS        41005
#define IDC_BUTTON_TEST_KEY             41006
#define IDC_BUTTON_DELETE_KEY           41007
#define IDC_STATIC_PROVIDER_LABEL       41008
#define IDD_SETTINGS_DIALOG             41010
#define IDC_LIST_MODELS                 41011
#define IDC_STATIC_SETTINGS_TITLE       41012
#define IDC_STATIC_SETTINGS_DESC        41013
#define IDC_BUTTON_SELECT_ALL           41014
#define IDC_BUTTON_DESELECT_ALL         41015
#define IDC_STATIC_MODEL_COUNT          41016
#define IDC_LIST_MODELS_EX              41017
#define IDC_STATIC_SETTINGS_TITLE2      41018
#define IDC_STATIC_SPEECH_STORAGE_ROOT  41019
#define IDC_EDIT_SPEECH_STORAGE_ROOT    41020
#define IDC_STATIC_SPEECH_MODEL_PATH    41021
#define IDC_EDIT_SPEECH_MODEL_PATH      41022
#define IDS_DEEPSEEK_DIALOG_TITLE       42000
#define IDS_DEEPSEEK_DIALOG_LABEL       42001
#define IDS_DEEPSEEK_STORED_MARKER      42002
#define IDS_BTN_SHOW                    42012
#define IDS_BTN_HIDE                    42013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        340
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1190
#define _APS_NEXT_SYMED_VALUE           340
#endif
#endif
