//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BlazeClawMFC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_BlazeClawMFCTYPE            130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_OVERVIEW_DIALOG             310
#define IDD_INSTANCE_DIALOG             311
#define IDD_SESSION_DIALOG              312
#define IDD_USAGE_DIALOG                313
#define IDD_TASK_DIALOG                 314
#define IDD_SKILL_DIALOG                315
#define IDD_LOG_DIALOG                  316
#define IDC_STATIC_TITLE                1000
#define IDC_STATIC_DESCRIPTION          1001
#define IDC_GROUP_GATEWAY               1002
#define IDC_STATIC_GATEWAY_DESC         1003
#define IDC_STATIC_WS_URL               1004
#define IDC_EDIT_WS_URL                 1005
#define IDC_STATIC_GATEWAY_TOKEN        1006
#define IDC_EDIT_GATEWAY_TOKEN          1007
#define IDC_STATIC_PASSWORD             1008
#define IDC_EDIT_PASSWORD               1009
#define IDC_STATIC_SESSION_KEY          1010
#define IDC_EDIT_SESSION_KEY            1011
#define IDC_STATIC_LANGUAGE             1012
#define IDC_COMBO_LANGUAGE              1013
#define IDC_BUTTON_CONNECT              1014
#define IDC_BUTTON_REFRESH              1015
#define IDC_STATIC_HINT                 1016
#define IDC_STATIC_INST_MAIN_TITLE      1017
#define IDC_STATIC_INST_MAIN_DESC       1018
#define IDC_GROUP_CONN_INST             1019
#define IDC_STATIC_CONN_SUBTITLE        1020
#define IDC_BUTTON_INST_REFRESH         1021
#define IDC_GROUP_INSTANCE_CARD         1022
#define IDC_STATIC_INSTANCE_DETAIL      1023
#define IDC_STATIC_INSTANCE_TAGS        1024
#define IDC_STATIC_INST_STATUS_JUST     1025
#define IDC_STATIC_INST_STATUS_LAST     1026
#define IDC_STATIC_INST_STATUS_BEACON   1027
#define IDC_STATIC_SESS_MAIN_TITLE      1028
#define IDC_STATIC_SESS_MAIN_DESC       1029
#define IDC_GROUP_SESS_CARD             1030
#define IDC_STATIC_SESS_EN_SUBTITLE     1031
#define IDC_BUTTON_SESS_REFRESH         1032
#define IDC_STATIC_ACTIVE_WITHIN_LABEL  1033
#define IDC_EDIT_ACTIVE_WITHIN_SEC      1034
#define IDC_STATIC_LIMIT_LABEL          1035
#define IDC_EDIT_LIMIT                  1036
#define IDC_CHECK_INCLUDE_GLOBAL        1037
#define IDC_CHECK_INCLUDE_UNKNOWN       1038
#define IDC_STATIC_SCORE_LABEL          1039
#define IDC_STATIC_HDR_KEY              1040
#define IDC_STATIC_HDR_LABEL            1041
#define IDC_STATIC_HDR_KIND             1042
#define IDC_STATIC_HDR_UPDATED          1043
#define IDC_STATIC_HDR_INDEX            1044
#define IDC_STATIC_HDR_THINKING         1045
#define IDC_STATIC_HDR_INSTANCE         1046
#define IDC_STATIC_HDR_REMAINING        1047
#define IDC_STATIC_HDR_ACTIONS          1048
#define IDC_STATIC_ROW_KEY              1049
#define IDC_EDIT_ROW_LABEL              1050
#define IDC_STATIC_ROW_KIND             1051
#define IDC_STATIC_ROW_UPDATED          1052
#define IDC_STATIC_ROW_INDEX            1053
#define IDC_COMBO_ROW_THINKING          1054
#define IDC_COMBO_ROW_INSTANCE          1055
#define IDC_COMBO_ROW_REMAINING         1056
#define IDC_BUTTON_ROW_DELETE           1057
#define IDC_STATIC_USAGE_MAIN_TITLE     1058
#define IDC_STATIC_USAGE_MAIN_DESC      1059
#define IDC_BUTTON_USAGE_TODAY          1060
#define IDC_BUTTON_USAGE_7D             1061
#define IDC_BUTTON_USAGE_30D            1062
#define IDC_EDIT_USAGE_DATE_FROM        1063
#define IDC_EDIT_USAGE_DATE_TO          1064
#define IDC_COMBO_USAGE_SCOPE           1065
#define IDC_RADIO_USAGE_TOKENS          1066
#define IDC_RADIO_USAGE_COST            1067
#define IDC_BUTTON_USAGE_REFRESH_TOP    1068
#define IDC_BUTTON_USAGE_EXPORT         1069
#define IDC_EDIT_USAGE_FILTER           1070
#define IDC_STATIC_USAGE_TIP            1071
#define IDC_GROUP_ACTIVITY_TIME         1072
#define IDC_STATIC_ACTIVITY_TITLE       1073
#define IDC_STATIC_ACTIVITY_SUB         1074
#define IDC_STATIC_ACTIVITY_TOKEN_COUNT 1075
#define IDC_STATIC_ACTIVITY_EMPTY       1076
#define IDC_GROUP_DAILY_USAGE           1077
#define IDC_STATIC_DAILY_TITLE          1078
#define IDC_STATIC_DAILY_EMPTY          1079
#define IDC_GROUP_USAGE_SESSIONS_PANEL  1080
#define IDC_STATIC_USAGE_SESS_TITLE     1081
#define IDC_STATIC_USAGE_SESS_COUNT     1082
#define IDC_BUTTON_USAGE_JUMP           1083
#define IDC_BUTTON_USAGE_VIEW           1083
#define IDC_BUTTON_USAGE_ERRORS         1084
#define IDC_BUTTON_USAGE_Recently       1084
#define IDC_BUTTON_USAGE_ALL_FILTER     1085
#define IDC_STATIC_USAGE_RECENT         1086
#define IDC_COMBO_USAGE_SORT            1087
#define IDC_BUTTON_USAGE_SESS_REFRESH   1088
#define IDC_STATIC_USAGE_SESS_EMPTY     1089
#define IDC_STATIC_USAGE_TO_LABEL       1090
#define IDC_STATIC_TASK_MAIN_TITLE      1091
#define IDC_STATIC_TASK_MAIN_DESC       1092
#define IDC_STATIC_SUM_PROXY_LBL        1093
#define IDC_STATIC_SUM_PROXY_VAL        1094
#define IDC_STATIC_SUM_COUNT_LBL        1095
#define IDC_STATIC_SUM_COUNT_VAL        1096
#define IDC_STATIC_SUM_NEXT_LBL         1097
#define IDC_STATIC_SUM_NEXT_VAL         1098
#define IDC_BUTTON_TASK_REFRESH_TOP     1099
#define IDC_GROUP_TASK_LIST             1100
#define IDC_EDIT_TASK_LIST_SEARCH       1101
#define IDC_COMBO_TASK_STARTUP          1102
#define IDC_COMBO_TASK_SCHEDULE         1103
#define IDC_COMBO_TASK_CONTROL          1104
#define IDC_COMBO_TASK_SORT             1105
#define IDC_COMBO_TASK_SORT_DIR         1106
#define IDC_BUTTON_TASK_LIST_SEARCH     1107
#define IDC_STATIC_TASK_LIST_EMPTY      1108
#define IDC_GROUP_RUN_HISTORY           1109
#define IDC_COMBO_HIST_CYCLE            1110
#define IDC_COMBO_HIST_HEALTH           1111
#define IDC_COMBO_HIST_SORT             1112
#define IDC_COMBO_HIST_STATUS           1113
#define IDC_COMBO_HIST_FILTER           1114
#define IDC_STATIC_HIST_EMPTY           1115
#define IDC_GROUP_CREATE_OUTER          1116
#define IDC_STATIC_CREATE_SUB           1117
#define IDC_GROUP_TASK_BASIC            1118
#define IDC_EDIT_TASK_NAME              1119
#define IDC_EDIT_TASK_DESC              1120
#define IDC_EDIT_TASK_FILE              1121
#define IDC_CHECK_TASK_NODES            1122
#define IDC_GROUP_TASK_SCHEDULE_FORM    1123
#define IDC_COMBO_SCHEDULE_TYPE         1124
#define IDC_EDIT_SCHEDULE_INTERVAL      1125
#define IDC_COMBO_SCHEDULE_UNIT         1126
#define IDC_GROUP_TASK_RUN_FORM         1127
#define IDC_EDIT_RUN_PATH               1128
#define IDC_COMBO_TRANSFER_MODE         1129
#define IDC_EDIT_RUN_MEMORY             1130
#define IDC_EDIT_CONCURRENCY            1131
#define IDC_EDIT_SCRIPT_ARGS            1132
#define IDC_GROUP_TASK_RESULT_FORM      1133
#define IDC_COMBO_RESULT_CHANNEL        1134
#define IDC_EDIT_RESULT_TAG             1135
#define IDC_EDIT_RESULT_RECIPIENTS      1136
#define IDC_BUTTON_TASK_CREATE          1137
#define IDC_STATIC_SKILL_PAGE_TITLE     1138
#define IDC_STATIC_SKILL_PAGE_DESC      1139
#define IDC_GROUP_SKILL_CARD            1140
#define IDC_STATIC_SKILL_CARD_TITLE     1141
#define IDC_STATIC_SKILL_CARD_SUB       1142
#define IDC_STATIC_SKILL_FILTER_LABEL   1143
#define IDC_EDIT_SKILL_SEARCH           1144
#define IDC_STATIC_SKILL_SHOWN_COUNT    1145
#define IDC_BUTTON_SKILL_REFRESH        1146
#define IDC_BTN_TOGGLE_BUILTIN          1147
#define IDC_LIST_SKILL_BUILTIN          1148
#define IDC_BTN_TOGGLE_EXTRA            1149
#define IDC_LIST_SKILL_EXTRA            1150
#define IDC_STATIC_LOG_PAGE_TITLE       1151
#define IDC_STATIC_LOG_PAGE_DESC        1152
#define IDC_BUTTON_LOG_REFRESH          1153
#define IDC_BUTTON_LOG_EXPORT           1154
#define IDC_STATIC_LOG_CARD_TITLE       1155
#define IDC_STATIC_LOG_CARD_SUB         1156
#define IDC_STATIC_LOG_FILTER_LABEL     1157
#define IDC_EDIT_LOG_SEARCH             1158
#define IDC_CHECK_LOG_AUTO_FOLLOW       1159
#define IDC_CHECK_LOG_TRACE             1160
#define IDC_CHECK_LOG_DEBUG             1161
#define IDC_CHECK_LOG_INFO              1162
#define IDC_CHECK_LOG_WARN              1163
#define IDC_CHECK_LOG_ERROR             1164
#define IDC_CHECK_LOG_FATAL             1165
#define IDC_STATIC_LOG_FILE_PATH        1166
#define IDC_LIST_LOG_ENTRIES            1167
#define IDC_BUTTON_TASK_LIST_RESET      1168
#define IDC_EDIT_HIST_TASK_NAME         1169
#define IDC_EDIT_HIST_DEPT              1170
#define IDC_BUTTON_HIST_QUERY           1171
#define IDC_COMBO_EXEC_MAP              1172
#define IDC_COMBO_EXEC_CONTENT          1173
#define IDC_EDIT_EXEC_TIMEOUT           1174
#define IDC_BUTTON_TASK_ADVANCED        1175
#define IDC_BUTTON_TASK_DELETE          1176
#define IDC_EDIT1                       1177
#define ID_WRITE_PASTEASHYPERLINK       32770
#define ID_EDIT_DOC                     32771
#define ID_EDIT_OVERVIEW                32772
#define ID_EDIT_CHAT                    32773
#define ID_EDIT_LOG                     32774
#define ID_EDIT_DEBUG                   32775
#define ID_EDIT_CONF                    32776
#define ID_EDIT_NODE                    32777
#define ID_EDIT_SKILL                   32778
#define ID_EDIT_Agent                   32779
#define ID_EDIT_AGENT1                  32779
#define ID_EDIT_TASK                    32780
#define ID_EDIT_USG                     32781
#define ID_EDIT_SESSION                 32782
#define ID_EDIT_INST                    32783
#define ID_EDIT_CHANNEL                 32784
#define ID_EXTENSION_DEEPSEEK           40101
#define IDD_APIKEY_DIALOG                41000
#define IDC_EDIT_APIKEY                  41001
// Localization strings
#define IDS_DEEPSEEK_DIALOG_TITLE        42000
#define IDS_DEEPSEEK_DIALOG_LABEL        42001
#define IDS_DEEPSEEK_STORED_MARKER       42002

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        317
#define _APS_NEXT_COMMAND_VALUE         32786
#define _APS_NEXT_CONTROL_VALUE         1178
#define _APS_NEXT_SYMED_VALUE           317
#endif
#endif
