import re
import glob
import os
from collections import defaultdict

TRACE_GLOB = '**/traces/*.log'
IO_GLOB = '**/traces/*io*.log'

stage_re = re.compile(r'pid=(\d+) tick=(\d+) stage=(.+)')
io_path_re = re.compile(r'path=(.+) exists=(true|false) statMs=(\d+)(?: size=(\d+))?')

runs = defaultdict(list)

for fname in glob.glob(TRACE_GLOB, recursive=True):
    with open(fname, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            m = stage_re.search(line)
            if m:
                pid = int(m.group(1))
                tick = int(m.group(2))
                stage = m.group(3).strip()
                runs[pid].append((tick, stage))

# Compute per-pid summaries
summaries = []
for pid, events in runs.items():
    events.sort()
    # find first InitInstance.begin and last InitInstance.completed.true for run
    begin = None
    completed = None
    sm_begin = None
    sm_after_local = None
    sm_before_local = None
    for tick, stage in events:
        if stage == 'InitInstance.begin' and begin is None:
            begin = tick
        if stage == 'InitInstance.completed.true':
            completed = tick
        if stage == 'ServiceManager.Start.begin' and sm_begin is None:
            sm_begin = tick
        if stage == 'ServiceManager.Start.localmodel.beforeLoad':
            sm_before_local = tick
        if stage == 'ServiceManager.Start.localmodel.afterLoad':
            sm_after_local = tick
    total_ms = None
    sm_local_load_ms = None
    sm_ms = None
    if begin is not None and completed is not None:
        total_ms = completed - begin
    if sm_before_local is not None and sm_after_local is not None:
        sm_local_load_ms = sm_after_local - sm_before_local
    if sm_begin is not None and (completed is not None):
        sm_ms = (completed - sm_begin) if completed is not None else None
    summaries.append({'pid':pid,'begin':begin,'completed':completed,'total_ms':total_ms,'sm_begin':sm_begin,'sm_ms':sm_ms,'sm_local_load_ms':sm_local_load_ms})

# Sort by total_ms desc
summaries.sort(key=lambda s: (s['total_ms'] if s['total_ms'] is not None else -1), reverse=True)

# Parse IO logs for largest files
files = []
for fname in glob.glob(IO_GLOB, recursive=True):
    with open(fname, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            m = io_path_re.search(line)
            if m:
                path = m.group(1).strip()
                exists = m.group(2) == 'true'
                statMs = int(m.group(3))
                size = int(m.group(4)) if m.group(4) else None
                files.append({'path':path,'exists':exists,'statMs':statMs,'size':size,'source':fname})

# pick top largest
files_with_size = [p for p in files if p['size'] is not None]
files_with_size.sort(key=lambda x: x['size'], reverse=True)

report_lines = []
report_lines.append('# Startup Profiling Summary')
report_lines.append('')
report_lines.append('Generated by blazeclaw/tools/analyze_startup_traces.py')
report_lines.append('')
report_lines.append('## Per-run startup durations')
report_lines.append('')
if not summaries:
    report_lines.append('No trace runs found.')
else:
    report_lines.append('| pid | total_ms | service_manager_total_ms | localmodel_load_ms |')
    report_lines.append('|---:|---:|---:|---:|')
    for s in summaries:
        report_lines.append(f"| {s['pid']} | {s['total_ms'] or 'n/a'} | {s['sm_ms'] or 'n/a'} | {s['sm_local_load_ms'] or 'n/a'} |")

report_lines.append('')
report_lines.append('## Top heavy files observed in IO traces')
report_lines.append('')
if not files_with_size:
    report_lines.append('No file size information found in IO traces.')
else:
    report_lines.append('| size(bytes) | path | statMs | source |')
    report_lines.append('|---:|---|---:|---|')
    for p in files_with_size[:25]:
        report_lines.append(f"| {p['size']} | {p['path']} | {p['statMs']} | {os.path.basename(p['source'])} |")

report_lines.append('')
report_lines.append('## Recommendations (automated analysis)')
report_lines.append('')
report_lines.append('- Local model artifacts are large (GBs). Consider lazy-loading or using quantized/smaller models for faster startup.')
report_lines.append('- Avoid synchronous probes that depend on model initialization during startup; defer or make async with timeout.')
report_lines.append('- Move heavy model loading off UI thread into background worker and mark readiness when complete.')
report_lines.append('- Re-run ETW capture elevated to get CPU sampling and function-level hotspots (WPR + WPA).')

out_path = 'blazeclaw/docs/reviews/STARTUP_PROFILING.md'
with open(out_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(report_lines))

print('Wrote', out_path)
