#include "pch.h"
#include "GatewayProtocolSchemaValidator.h"

namespace blazeclaw::gateway::protocol {
    // Request no-params validation entries
    const std::vector<std::string> noParamsMethods = {
        "gateway.config.session",
        "gateway.transport.policy.session",
        "gateway.events.sessionKey",
        "gateway.models.session",
        "gateway.tools.mapper",
        "gateway.tools.executions.count",
        "gateway.tools.executions.latest",
        "gateway.tools.executions.clear",
        "gateway.runtime.orchestration.load",
        "gateway.runtime.streaming.buffer",
        "gateway.models.failover.override",
        "gateway.runtime.orchestration.saturation",
        "gateway.runtime.streaming.throttle",
        "gateway.models.failover.override.clear",
        "gateway.runtime.orchestration.pressure",
        "gateway.runtime.streaming.pacing",
        "gateway.models.failover.override.status",
        "gateway.runtime.orchestration.headroom",
        "gateway.runtime.streaming.jitter",
        "gateway.models.failover.override.history",
        "gateway.runtime.orchestration.balance",
        "gateway.runtime.streaming.drift",
        "gateway.models.failover.override.metrics",
        "gateway.runtime.orchestration.efficiency",
        "gateway.runtime.streaming.variance",
        "gateway.models.failover.override.window",
        "gateway.runtime.orchestration.utilization",
        "gateway.runtime.streaming.deviation",
        "gateway.models.failover.override.digest",
        "gateway.runtime.orchestration.capacity",
        "gateway.runtime.streaming.alignment",
        "gateway.models.failover.override.timeline",
        "gateway.runtime.orchestration.occupancy",
        "gateway.runtime.streaming.skew",
        "gateway.models.failover.override.catalog",
        "gateway.runtime.orchestration.elasticity",
        "gateway.runtime.streaming.dispersion",
        "gateway.models.failover.override.registry",
        "gateway.runtime.orchestration.cohesion",
        "gateway.runtime.streaming.curvature",
        "gateway.models.failover.override.matrix",
        "gateway.runtime.orchestration.resilience",
        "gateway.runtime.streaming.smoothness",
        "gateway.models.failover.override.snapshot",
        "gateway.runtime.orchestration.readiness",
        "gateway.runtime.streaming.harmonics",
        "gateway.models.failover.override.pointer",
        "gateway.runtime.orchestration.contention",
        "gateway.runtime.streaming.phase",
        "gateway.models.failover.override.state",
        "gateway.runtime.orchestration.fairness",
        "gateway.runtime.streaming.tempo",
        "gateway.models.failover.override.profile",
        "gateway.runtime.orchestration.equilibrium",
        "gateway.runtime.orchestration.steadiness",
        "gateway.runtime.streaming.temporal",
        "gateway.runtime.streaming.consistency",
        "gateway.models.failover.override.audit",
        "gateway.runtime.orchestration.parity",
        "gateway.runtime.orchestration.stabilityIndex",
        "gateway.runtime.streaming.spectral",
        "gateway.runtime.streaming.envelope",
        "gateway.models.failover.override.checkpoint"
    };
} // namespace blazeclaw::gateway::protocol
